import React, { useState, useRef, useEffect } from 'react';
import { SettingsState, Device, AppMode, Room, SoundType } from '../types';
import { Wifi, Server, X, Smartphone, Droplets, Trash2, Activity, Power, Code, Volume2, Home, Check, Copy, Moon, Sun } from 'lucide-react';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  settings: SettingsState;
  onUpdateSettings: (s: SettingsState) => void;
  devices: Device[];
  rooms: Room[];
  onUpdateDevice: (d: Device) => void;
  onDeleteDevice: (id: string) => void;
  onSystemSync: () => void;
}

const SettingsModal: React.FC<SettingsModalProps> = ({ 
  isOpen, onClose, settings, onUpdateSettings, devices, rooms, onUpdateDevice, onDeleteDevice, onSystemSync
}) => {
  const [activeTab, setActiveTab] = useState<'wifi' | 'devices' | 'general' | 'tank' | 'code'>('general');
  const [variablePopup, setVariablePopup] = useState<{code: string, name: string} | null>(null);
  const pressTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const [showAuth, setShowAuth] = useState(false);
  const [authInput, setAuthInput] = useState('');
  const [authError, setAuthError] = useState(false);

  const [isSyncing, setIsSyncing] = useState(false);
  const [syncProgress, setSyncProgress] = useState(0);
  const [syncStep, setSyncStep] = useState('');

  const [secretCount, setSecretCount] = useState(0);
  const [showDevTab, setShowDevTab] = useState(false);
  const [copyFeedback, setCopyFeedback] = useState(false);

  useEffect(() => {
    if (!isOpen) {
        setVariablePopup(null);
        setShowAuth(false);
        setAuthInput('');
        setAuthError(false);
        setSecretCount(0);
        setCopyFeedback(false);
        setIsSyncing(false);
        setSyncProgress(0);
        setShowDevTab(false);
        setActiveTab('general'); 
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleTitleClick = () => {
    setSecretCount(prev => {
        const newCount = prev + 1;
        if (newCount >= 5) {
            setShowDevTab(true);
            setActiveTab('code');
            return 0;
        }
        return newCount;
    });
  };

  const initiateModeToggle = () => {
    if (settings.controlMode === AppMode.MANUAL) {
        setShowAuth(true);
        setAuthError(false);
        setAuthInput('');
    } else {
        onUpdateSettings({ ...settings, controlMode: AppMode.MANUAL });
    }
  };

  const confirmAuth = () => {
    if (authInput === 'hodo8212') {
        setIsSyncing(true);
        setAuthError(false);
        
        setSyncStep('Initializing Hardware Link...');
        setSyncProgress(10);

        setTimeout(() => {
           setSyncStep('Scanning Mesh Network...');
           setSyncProgress(35);
        }, 1200);

        setTimeout(() => {
           setSyncStep('Fetching GPIO States...');
           setSyncProgress(60);
        }, 2500);

        setTimeout(() => {
           setSyncStep('Calibrating Sensors...');
           setSyncProgress(85);
           onSystemSync();
        }, 3800);

        setTimeout(() => {
           setSyncStep('Optimization Complete');
           setSyncProgress(100);
           onUpdateSettings({ ...settings, controlMode: AppMode.REMOTE });
           setIsSyncing(false);
           setShowAuth(false);
           setAuthInput('');
        }, 5000); 
        
    } else {
        setAuthError(true);
    }
  };

  const generateArduinoCode = () => {
      const timestamp = new Date().toLocaleString();
      let code = `/* \n  HomeControl ESP8266 Configuration \n  Generated: ${timestamp}\n  Auto-generated by HomeControl Web App\n*/\n\n`;
      
      code += `// --- WiFi Configuration ---\n`;
      code += `#define WIFI_SSID "${settings.wifiSSID}"\n`;
      code += `#define WIFI_PASS "${settings.wifiPass}"\n\n`;

      code += `// --- System Settings ---\n`;
      code += `const int PUMP_LOW_THRESHOLD = ${settings.pumpLowThreshold};\n`;
      code += `const int PUMP_HIGH_THRESHOLD = ${settings.pumpHighThreshold};\n\n`;

      code += `// --- Device Pins & Variables ---\n`;
      
      devices.forEach(d => {
          const varBase = d.name.trim().replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
          const roomName = rooms.find(r => r.id === d.roomId)?.name || 'Unknown';
          
          code += `\n// Device: ${d.name} (Room: ${roomName}, Type: ${d.type})\n`;
          code += `#define ${varBase.toUpperCase()}_PIN ${d.gpioPin}\n`;
          code += `String ${varBase}_id = "${d.id}";\n`;
          code += `bool ${varBase}_state = false; // Always init as false for safety\n`;
          code += `int ${varBase}_value = ${d.value}; // Range: 0-100 or 1-5\n`;
      });

      return code;
  };

  const copyToClipboard = () => {
      navigator.clipboard.writeText(generateArduinoCode());
      setCopyFeedback(true);
      setTimeout(() => setCopyFeedback(false), 2000);
  };

  const startPress = (device: Device, type: 'status' | 'fault') => {
    pressTimer.current = setTimeout(() => {
        const varName = device.name.trim().replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
        const suffix = type === 'status' ? '_state' : '_faulty';
        const code = `bool ${varName}${suffix} = false;`;
        setVariablePopup({ code, name: device.name });
    }, 800);
  };

  const endPress = () => {
    if (pressTimer.current) {
        clearTimeout(pressTimer.current);
        pressTimer.current = null;
    }
  };

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center bg-gray-900/40 dark:bg-black/60 backdrop-blur-lg p-4 animate-in fade-in duration-300">
      <div className="
        w-full max-w-3xl rounded-[2.5rem] overflow-hidden flex flex-col max-h-[90vh] relative transition-colors
        bg-gradient-to-br from-white/90 via-white/80 to-white/60 dark:from-gray-900/90 dark:via-gray-900/80 dark:to-gray-900/60
        border border-white/50 dark:border-white/10 shadow-2xl backdrop-blur-3xl
      ">
        
        {variablePopup && (
            <div className="absolute inset-0 z-50 bg-white/30 dark:bg-black/50 backdrop-blur-xl flex items-center justify-center p-6 animate-in fade-in duration-200">
                <div className="bg-white/90 dark:bg-gray-800/90 border border-emerald-200 dark:border-emerald-800 p-6 rounded-2xl w-full max-w-md shadow-2xl relative backdrop-blur-md">
                    <button 
                        onClick={() => setVariablePopup(null)}
                        className="absolute top-4 right-4 text-gray-400 hover:text-gray-800 dark:hover:text-gray-200"
                    >
                        <X size={20} />
                    </button>
                    <div className="flex items-center gap-3 text-emerald-600 dark:text-emerald-400 mb-4">
                        <Code size={24} />
                        <h3 className="font-bold text-lg">Quick Variable</h3>
                    </div>
                    <p className="text-gray-600 dark:text-gray-300 text-sm mb-2 font-mono">
                        Variable for <span className="text-emerald-600 dark:text-emerald-400 font-semibold">{variablePopup.name}</span>:
                    </p>
                    <div className="bg-gray-50 dark:bg-gray-900 p-4 rounded-xl border border-gray-200 dark:border-gray-700 font-mono text-sm text-emerald-600 dark:text-emerald-400 select-all shadow-inner">
                        <pre>{variablePopup.code}</pre>
                    </div>
                </div>
            </div>
        )}

        {/* Header */}
        <div className="flex justify-between items-center p-8 pb-4 border-b border-gray-200/50 dark:border-gray-700/50 bg-white/20 dark:bg-white/5">
          <h2 
            className="text-3xl font-bold text-gray-900 dark:text-white select-none cursor-pointer active:scale-95 transition-transform tracking-tight" 
            onClick={handleTitleClick}
            title="Tap 5 times for Developer Menu"
          >
            Settings {secretCount > 0 && secretCount < 5 && <span className="text-xs text-emerald-600 font-normal">({5 - secretCount})</span>}
          </h2>
          <button onClick={onClose} className="p-3 hover:bg-black/5 dark:hover:bg-white/10 rounded-full text-gray-400 hover:text-gray-800 dark:hover:text-gray-200 transition-colors">
            <X size={24} />
          </button>
        </div>

        {/* Tabs - Fixed Layout */}
        <div className="border-b border-gray-200/50 dark:border-gray-700/50 bg-white/10 dark:bg-white/5">
           <div className="flex px-8 pt-4 pb-2 space-x-2 overflow-x-auto custom-scrollbar">
             <button 
                onClick={() => setActiveTab('general')}
                className={`px-4 py-2.5 text-sm font-bold rounded-xl transition-all whitespace-nowrap tracking-wide flex-shrink-0 mb-2 border ${activeTab === 'general' ? 'bg-emerald-100/50 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 border-emerald-200/50 dark:border-emerald-800/50' : 'text-gray-500 dark:text-gray-400 hover:bg-gray-100/50 dark:hover:bg-gray-800/50 border-transparent'}`}
             >
               General & Alerts
             </button>
             <button 
                onClick={() => setActiveTab('tank')}
                className={`px-4 py-2.5 text-sm font-bold rounded-xl transition-all whitespace-nowrap tracking-wide flex-shrink-0 mb-2 border ${activeTab === 'tank' ? 'bg-emerald-100/50 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 border-emerald-200/50 dark:border-emerald-800/50' : 'text-gray-500 dark:text-gray-400 hover:bg-gray-100/50 dark:hover:bg-gray-800/50 border-transparent'}`}
             >
               Water Tank
             </button>
             <button 
                onClick={() => setActiveTab('wifi')}
                className={`px-4 py-2.5 text-sm font-bold rounded-xl transition-all whitespace-nowrap tracking-wide flex-shrink-0 mb-2 border ${activeTab === 'wifi' ? 'bg-emerald-100/50 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 border-emerald-200/50 dark:border-emerald-800/50' : 'text-gray-500 dark:text-gray-400 hover:bg-gray-100/50 dark:hover:bg-gray-800/50 border-transparent'}`}
             >
               WiFi Configuration
             </button>
             <button 
                onClick={() => setActiveTab('devices')}
                className={`px-4 py-2.5 text-sm font-bold rounded-xl transition-all whitespace-nowrap tracking-wide flex-shrink-0 mb-2 border ${activeTab === 'devices' ? 'bg-emerald-100/50 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 border-emerald-200/50 dark:border-emerald-800/50' : 'text-gray-500 dark:text-gray-400 hover:bg-gray-100/50 dark:hover:bg-gray-800/50 border-transparent'}`}
             >
               ESP Device Management
             </button>
             {showDevTab && (
               <button 
                   onClick={() => setActiveTab('code')}
                   className={`px-4 py-2.5 text-sm font-bold rounded-xl transition-all whitespace-nowrap tracking-wide flex-shrink-0 mb-2 flex items-center gap-2 border ${activeTab === 'code' ? 'bg-purple-100/50 dark:bg-purple-900/30 text-purple-700 dark:text-purple-400 border-purple-200/50 dark:border-purple-800/50' : 'text-gray-500 dark:text-gray-400 hover:bg-gray-100/50 dark:hover:bg-gray-800/50 border-transparent'}`}
               >
                   <Code size={14} /> Arduino Code
               </button>
             )}
           </div>
        </div>

        {/* Content */}
        <div className="p-8 overflow-y-auto custom-scrollbar">
          
          {activeTab === 'general' && (
            <div className="space-y-6">
              
              {/* Theme Toggle */}
              <div className="bg-white/40 dark:bg-white/5 p-6 rounded-3xl border border-white/50 dark:border-white/10 backdrop-blur-md shadow-sm flex items-center justify-between">
                <div>
                  <h3 className="text-gray-900 dark:text-white font-bold text-lg flex items-center gap-2">
                    {settings.theme === 'LIGHT' ? <Sun size={20} className="text-amber-500" /> : <Moon size={20} className="text-blue-400" />}
                    Appearance
                  </h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Switch between light and dark mode</p>
                </div>
                <div className="flex bg-gray-200/50 dark:bg-black/30 p-1.5 rounded-2xl backdrop-blur-sm">
                   <button 
                     onClick={() => onUpdateSettings({...settings, theme: 'LIGHT'})}
                     className={`p-3 rounded-xl transition-all ${settings.theme === 'LIGHT' ? 'bg-white dark:bg-gray-700 shadow-md text-amber-500 scale-105' : 'text-gray-400 hover:text-gray-600'}`}
                   >
                     <Sun size={20} />
                   </button>
                   <button 
                     onClick={() => onUpdateSettings({...settings, theme: 'DARK'})}
                     className={`p-3 rounded-xl transition-all ${settings.theme === 'DARK' ? 'bg-white dark:bg-gray-600 shadow-md text-blue-400 scale-105' : 'text-gray-400 hover:text-gray-300'}`}
                   >
                     <Moon size={20} />
                   </button>
                </div>
              </div>

              <div className="bg-white/40 dark:bg-white/5 p-6 rounded-3xl border border-white/50 dark:border-white/10 relative overflow-hidden backdrop-blur-md shadow-sm">
                
                {isSyncing ? (
                    <div className="flex flex-col items-center justify-center py-6 space-y-4 animate-in fade-in zoom-in duration-300">
                        <div className="relative">
                            <Activity className="text-emerald-500 animate-pulse drop-shadow-md" size={48} />
                            <div className="absolute inset-0 bg-emerald-500/10 blur-xl rounded-full animate-ping"></div>
                        </div>
                        
                        <div className="w-full max-w-sm space-y-2">
                             <div className="flex justify-between text-xs font-mono text-emerald-700 dark:text-emerald-400">
                                 <span>{syncStep}</span>
                                 <span>{syncProgress}%</span>
                             </div>
                             <div className="w-full bg-gray-200 dark:bg-gray-700 h-2 rounded-full overflow-hidden border border-gray-300 dark:border-gray-600 shadow-inner">
                                <div 
                                    className="h-full bg-gradient-to-r from-emerald-500 to-emerald-300 transition-all duration-700 ease-out relative overflow-hidden" 
                                    style={{width: `${syncProgress}%`}}
                                >
                                    <div className="absolute inset-0 bg-[linear-gradient(90deg,transparent,rgba(255,255,255,0.4),transparent)] animate-shimmer" style={{ backgroundSize: '200% 100%' }}></div>
                                </div>
                             </div>
                        </div>
                        <p className="text-xs text-gray-500 dark:text-gray-400 font-mono animate-pulse">Establishing secure handshake with mesh nodes...</p>
                    </div>
                ) : (
                    <div className="flex justify-between items-center mb-2">
                    <div className="flex items-center gap-4">
                        <div className={`p-3.5 rounded-2xl ${settings.controlMode === AppMode.REMOTE ? 'bg-emerald-100/60 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400' : 'bg-gray-100/60 dark:bg-gray-800/60 text-gray-400 dark:text-gray-500'}`}>
                        <Smartphone size={24} />
                        </div>
                        <div>
                        <h3 className="text-gray-900 dark:text-white font-bold text-lg">Control Mode</h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400">{settings.controlMode === AppMode.REMOTE ? 'Remote (Cloud/Auto)' : 'Manual (Local WiFi)'}</p>
                        </div>
                    </div>

                    {!showAuth ? (
                        <button 
                            onClick={initiateModeToggle}
                            className="px-6 py-3 bg-white/50 dark:bg-white/5 border border-white/50 dark:border-white/10 text-emerald-600 dark:text-emerald-400 hover:bg-white/80 dark:hover:bg-white/10 rounded-2xl text-sm font-bold transition-all shadow-sm hover:scale-105"
                        >
                            Switch to {settings.controlMode === AppMode.REMOTE ? 'Manual' : 'Remote'}
                        </button>
                    ) : (
                        <div className="flex items-center gap-2 animate-in fade-in slide-in-from-right duration-200">
                            <input 
                                type="password" 
                                autoFocus
                                placeholder="Auth Code"
                                value={authInput}
                                onChange={(e) => setAuthInput(e.target.value)}
                                className={`w-32 bg-white/50 dark:bg-black/30 border rounded-xl px-3 py-2 text-sm text-gray-900 dark:text-white focus:outline-none backdrop-blur-sm ${authError ? 'border-red-500' : 'border-emerald-500 focus:ring-2 focus:ring-emerald-200 dark:focus:ring-emerald-800'}`}
                                onKeyDown={(e) => e.key === 'Enter' && confirmAuth()}
                            />
                            <button onClick={confirmAuth} className="p-2 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 rounded-xl hover:bg-emerald-200 dark:hover:bg-emerald-900/50 border border-emerald-200 dark:border-emerald-800">
                                <Check size={18} />
                            </button>
                            <button onClick={() => setShowAuth(false)} className="p-2 bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 rounded-xl hover:bg-red-200 dark:hover:bg-red-900/50 border border-red-200 dark:border-red-800">
                                <X size={18} />
                            </button>
                        </div>
                    )}
                    </div>
                )}
                
                {!isSyncing && authError && <p className="text-xs text-red-500 text-right mt-1 absolute bottom-2 right-5">Incorrect Authentication Code</p>}
              </div>

              <div className="bg-white/40 dark:bg-white/5 p-6 rounded-3xl border border-white/50 dark:border-white/10 backdrop-blur-md shadow-sm">
                 <h3 className="text-gray-900 dark:text-white font-bold text-lg mb-4 flex items-center gap-2">
                    <Home size={20} className="text-emerald-500" /> Home Configuration
                </h3>
                <div>
                   <label className="text-xs text-gray-500 dark:text-gray-400 block mb-2 font-mono font-bold tracking-wider">HOME NAME</label>
                   <input 
                    type="text" 
                    value={settings.homeName}
                    onChange={(e) => onUpdateSettings({...settings, homeName: e.target.value})}
                    className="w-full bg-white/50 dark:bg-black/20 border border-gray-200 dark:border-gray-700 rounded-2xl px-4 py-3 text-gray-900 dark:text-white focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-200 dark:focus:ring-emerald-800 transition-colors backdrop-blur-sm"
                    placeholder="e.g. My Smart Home"
                  />
                </div>
              </div>

              <div className="bg-white/40 dark:bg-white/5 p-6 rounded-3xl border border-white/50 dark:border-white/10 backdrop-blur-md shadow-sm">
                 <h3 className="text-gray-900 dark:text-white font-bold text-lg mb-4 flex items-center gap-2">
                    <Volume2 size={20} className="text-emerald-500" /> Sound & Notifications
                </h3>
                <div className="space-y-4">
                    <div className="flex items-center justify-between">
                        <label className="text-sm text-gray-600 dark:text-gray-300 font-medium">Play Sound on Alert</label>
                        <div 
                            onClick={() => onUpdateSettings({...settings, soundEnabled: !settings.soundEnabled})}
                            className={`w-14 h-8 rounded-full p-1 cursor-pointer transition-colors border border-transparent ${settings.soundEnabled ? 'bg-emerald-500 shadow-lg shadow-emerald-200 dark:shadow-emerald-900' : 'bg-gray-300 dark:bg-gray-600'}`}
                        >
                            <div className={`w-6 h-6 bg-white rounded-full transition-transform shadow-sm ${settings.soundEnabled ? 'translate-x-6' : 'translate-x-0'}`} />
                        </div>
                    </div>
                    
                    {settings.soundEnabled && (
                         <div className="grid grid-cols-3 gap-3 mt-4">
                            {(['BEEP', 'CHIME', 'ALARM'] as SoundType[]).map(sound => (
                                <button
                                    key={sound}
                                    onClick={() => onUpdateSettings({...settings, alertSound: sound})}
                                    className={`py-3 px-3 rounded-xl text-xs font-bold border transition-all ${
                                        settings.alertSound === sound 
                                        ? 'bg-emerald-100/50 dark:bg-emerald-900/30 border-emerald-500 dark:border-emerald-700 text-emerald-600 dark:text-emerald-400 shadow-sm scale-105' 
                                        : 'bg-white/40 dark:bg-white/5 border-transparent text-gray-500 dark:text-gray-400 hover:bg-white/60 dark:hover:bg-white/10'
                                    }`}
                                >
                                    {sound}
                                </button>
                            ))}
                         </div>
                    )}
                </div>
              </div>
            </div>
          )}

          {activeTab === 'tank' && (
             <div className="space-y-6">
                 <div className="flex items-center gap-3 text-emerald-700 dark:text-emerald-400 bg-emerald-100/50 dark:bg-emerald-900/20 p-5 rounded-2xl mb-4 border border-emerald-100 dark:border-emerald-800 backdrop-blur-sm">
                    <Droplets size={24} />
                    <span className="text-sm font-medium">Configure automation thresholds for the water pump.</span>
                 </div>
                 
                 <div className="bg-white/40 dark:bg-white/5 p-6 rounded-3xl border border-white/50 dark:border-white/10 space-y-8 backdrop-blur-md shadow-sm">
                    <div>
                        <div className="flex justify-between mb-3">
                            <label className="text-sm text-gray-600 dark:text-gray-300 font-bold">Auto-Start Level (Low)</label>
                            <span className="text-emerald-600 dark:text-emerald-400 font-bold font-mono bg-emerald-50 dark:bg-emerald-900/30 px-2 py-1 rounded-lg">{settings.pumpLowThreshold}%</span>
                        </div>
                        <input 
                            type="range" 
                            min="5" 
                            max="50" 
                            value={settings.pumpLowThreshold}
                            onChange={(e) => onUpdateSettings({...settings, pumpLowThreshold: parseInt(e.target.value)})}
                            className="w-full h-3 bg-gray-200 dark:bg-gray-700 rounded-lg appearance-none cursor-pointer accent-emerald-500"
                        />
                        <p className="text-xs text-gray-400 dark:text-gray-500 mt-2 font-medium">Pump starts automatically when level drops below this value.</p>
                    </div>

                    <div className="border-t border-gray-200/30 dark:border-white/10 pt-6">
                        <div className="flex justify-between mb-3">
                            <label className="text-sm text-gray-600 dark:text-gray-300 font-bold">Auto-Stop Level (High)</label>
                            <span className="text-emerald-600 dark:text-emerald-400 font-bold font-mono bg-emerald-50 dark:bg-emerald-900/30 px-2 py-1 rounded-lg">{settings.pumpHighThreshold}%</span>
                        </div>
                         <input 
                            type="range" 
                            min="51" 
                            max="100" 
                            value={settings.pumpHighThreshold}
                            onChange={(e) => onUpdateSettings({...settings, pumpHighThreshold: parseInt(e.target.value)})}
                            className="w-full h-3 bg-gray-200 dark:bg-gray-700 rounded-lg appearance-none cursor-pointer accent-emerald-500"
                        />
                         <p className="text-xs text-gray-400 dark:text-gray-500 mt-2 font-medium">Pump stops automatically when level exceeds this value.</p>
                    </div>
                 </div>
             </div>
          )}

          {activeTab === 'wifi' && (
            <div className="space-y-4">
               <div className="flex items-center gap-3 text-amber-700 dark:text-amber-400 bg-amber-100/50 dark:bg-amber-900/20 p-5 rounded-2xl mb-4 border border-amber-100 dark:border-amber-800 backdrop-blur-sm">
                  <Wifi size={24} />
                  <span className="text-sm font-medium">These settings configure the local offline ESP8266 network.</span>
               </div>
               <div>
                  <label className="text-xs text-gray-500 dark:text-gray-400 block mb-2 font-mono font-bold tracking-wider">WIFI SSID</label>
                  <input 
                    type="text" 
                    value={settings.wifiSSID}
                    onChange={(e) => onUpdateSettings({...settings, wifiSSID: e.target.value})}
                    className="w-full bg-white/50 dark:bg-black/20 border border-gray-200 dark:border-gray-700 rounded-2xl px-4 py-3 text-gray-900 dark:text-white focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-200 dark:focus:ring-emerald-800 transition-colors backdrop-blur-sm"
                    placeholder="Home_WiFi_2.4G"
                  />
               </div>
               <div>
                  <label className="text-xs text-gray-500 dark:text-gray-400 block mb-2 font-mono font-bold tracking-wider">WIFI PASSWORD</label>
                  <input 
                    type="password" 
                    value={settings.wifiPass}
                    onChange={(e) => onUpdateSettings({...settings, wifiPass: e.target.value})}
                    className="w-full bg-white/50 dark:bg-black/20 border border-gray-200 dark:border-gray-700 rounded-2xl px-4 py-3 text-gray-900 dark:text-white focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-200 dark:focus:ring-emerald-800 transition-colors backdrop-blur-sm"
                    placeholder="••••••••"
                  />
               </div>
            </div>
          )}

          {activeTab === 'devices' && (
            <div className="space-y-4">
                <div className="flex items-center gap-3 text-purple-700 dark:text-purple-400 bg-purple-100/50 dark:bg-purple-900/20 p-5 rounded-2xl mb-4 border border-purple-100 dark:border-purple-800 backdrop-blur-sm">
                  <Server size={24} />
                  <span className="text-sm font-medium">Manage ESP devices and pin mappings. <br/><span className="text-xs text-purple-500 dark:text-purple-400 opacity-70">Long press indicators to get Arduino variable names.</span></span>
                </div>

                {devices.map((device) => {
                     const roomName = rooms.find(r => r.id === device.roomId)?.name || 'Unknown Room';
                     return (
                        <div key={device.id} className="bg-white/40 dark:bg-white/5 p-6 rounded-3xl border border-white/50 dark:border-white/10 flex flex-col gap-5 backdrop-blur-md shadow-sm">
                            <div className="flex flex-col md:flex-row gap-4">
                                <div className="flex-1">
                                    <label className="text-[10px] text-gray-400 uppercase font-bold tracking-wider mb-1 block font-mono">IP Address</label>
                                    <input 
                                        type="text"
                                        className="w-full bg-white/50 dark:bg-black/20 border border-gray-200 dark:border-gray-700 rounded-xl px-3 py-2 text-sm font-mono text-emerald-600 dark:text-emerald-400 focus:border-emerald-500 outline-none transition-colors backdrop-blur-sm"
                                        value={device.ipAddress || ''}
                                        onChange={(e) => onUpdateDevice({...device, ipAddress: e.target.value})}
                                        placeholder="192.168.1.X"
                                    />
                                </div>
                                <div className="flex-[0.7]">
                                    <label className="text-[10px] text-gray-400 uppercase font-bold tracking-wider mb-1 block font-mono">GPIO PIN</label>
                                    <input 
                                        type="number"
                                        className="w-full bg-white/50 dark:bg-black/20 border border-gray-200 dark:border-gray-700 rounded-xl px-3 py-2 text-sm font-mono text-amber-600 dark:text-amber-400 focus:border-amber-500 outline-none transition-colors backdrop-blur-sm"
                                        value={device.gpioPin}
                                        onChange={(e) => onUpdateDevice({...device, gpioPin: parseInt(e.target.value)})}
                                        placeholder="Pin #"
                                    />
                                </div>
                                <div className="flex-[2]">
                                    <label className="text-[10px] text-gray-400 uppercase font-bold tracking-wider mb-1 block font-mono">Device Name</label>
                                    <input 
                                        type="text"
                                        className="w-full bg-white/50 dark:bg-black/20 border border-gray-200 dark:border-gray-700 rounded-xl px-3 py-2 text-sm text-gray-900 dark:text-white focus:border-emerald-500 outline-none transition-colors backdrop-blur-sm"
                                        value={device.name}
                                        onChange={(e) => onUpdateDevice({...device, name: e.target.value})}
                                        placeholder="Device Name"
                                    />
                                </div>
                            </div>
                            
                            <div className="flex flex-col sm:flex-row sm:items-center justify-between border-t border-gray-200/50 dark:border-gray-700/50 pt-4 gap-3">
                                <div className="flex items-center gap-4">
                                    <div className="text-xs text-gray-400 dark:text-gray-500 font-bold">{roomName} • {device.type}</div>
                                    
                                    <div 
                                        onMouseDown={() => startPress(device, 'status')}
                                        onMouseUp={endPress}
                                        onMouseLeave={endPress}
                                        onTouchStart={() => startPress(device, 'status')}
                                        onTouchEnd={endPress}
                                        className={`flex items-center gap-2 cursor-help select-none bg-gray-100/50 dark:bg-gray-800/50 px-3 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 transition-colors ${device.isOn ? 'text-emerald-600 dark:text-emerald-400' : 'text-gray-400 dark:text-gray-500'}`}
                                        title="Power Status (Read Only)"
                                    >
                                        <Power size={14} />
                                        <span className="text-xs font-bold">{device.isOn ? 'ACTIVE' : 'INACTIVE'}</span>
                                    </div>

                                    <div 
                                        onMouseDown={() => startPress(device, 'fault')}
                                        onMouseUp={endPress}
                                        onMouseLeave={endPress}
                                        onTouchStart={() => startPress(device, 'fault')}
                                        onTouchEnd={endPress}
                                        className={`flex items-center gap-2 cursor-help select-none bg-gray-100/50 dark:bg-gray-800/50 px-3 py-1.5 rounded-lg border border-gray-200 dark:border-gray-700 transition-colors ${device.isFaulty ? 'text-red-500 dark:text-red-400' : 'text-emerald-600 dark:text-emerald-400'}`}
                                        title="System Status (Read Only)"
                                    >
                                        <Activity size={14} />
                                        <span className="text-xs font-bold">{device.isFaulty ? 'FAULTY' : 'HEALTHY'}</span>
                                    </div>
                                </div>

                                <button 
                                    onClick={() => onDeleteDevice(device.id)}
                                    className="flex items-center justify-center gap-2 px-4 py-2 rounded-xl bg-red-50 dark:bg-red-900/10 text-red-500 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-900/30 transition-colors text-xs font-bold border border-red-100 dark:border-red-900/30"
                                >
                                    <Trash2 size={16} /> Delete
                                </button>
                            </div>
                        </div>
                     );
                })}
            </div>
          )}

          {activeTab === 'code' && (
            <div className="space-y-4 h-full flex flex-col">
                <div className="flex items-center justify-between bg-purple-100/50 dark:bg-purple-900/20 p-5 rounded-2xl mb-2 border border-purple-100 dark:border-purple-800 backdrop-blur-sm">
                  <div className="flex items-center gap-3 text-purple-600 dark:text-purple-400">
                    <Code size={24} />
                    <div>
                        <span className="text-sm font-bold block">Arduino Configuration Generator</span>
                        <span className="text-xs opacity-70">Copy this code into your ESP8266 sketch</span>
                    </div>
                  </div>
                  <button 
                    onClick={copyToClipboard}
                    className="flex items-center gap-2 px-4 py-2 bg-purple-200/50 dark:bg-purple-800/30 hover:bg-purple-200 dark:hover:bg-purple-800/50 text-purple-700 dark:text-purple-300 rounded-xl transition-colors text-xs font-bold border border-purple-200/50 dark:border-purple-700/50"
                  >
                    {copyFeedback ? <Check size={16}/> : <Copy size={16} />}
                    {copyFeedback ? 'COPIED!' : 'COPY CODE'}
                  </button>
                </div>
                
                <div className="flex-1 bg-gray-900 border border-gray-800 rounded-2xl p-5 overflow-hidden relative group shadow-inner">
                    <pre className="text-xs font-mono text-emerald-400 whitespace-pre-wrap h-full overflow-y-auto custom-scrollbar select-all">
                        {generateArduinoCode()}
                    </pre>
                </div>
            </div>
          )}

        </div>
      </div>
    </div>
  );
};

export default SettingsModal;